/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  MoodLogs: () => import('#controllers/mood_logs_controller'),
  Stats: () => import('#controllers/stats_controller'),
  WebsiteVisits: () => import('#controllers/website_visits_controller'),
}
