import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  protected tableName = 'mood_logs'

  async up() {
    this.schema.createTable(this.tableName, (table) => {
      table.uuid('id').primary().defaultTo(this.db.rawQuery('gen_random_uuid()').knexQuery)
      // 1 = very unpleasant … 7 = very pleasant
      table.integer('mood').notNullable().checkBetween([1, 7])
      // When the user actually logged the mood (client-side time)
      table.timestamp('timestamp', { useTz: true }).notNullable()
      // UUID generated by the extension — used for server-side deduplication
      table.string('client_id').notNullable().unique()
      table
        .timestamp('created_at', { useTz: true })
        .notNullable()
        .defaultTo(this.db.rawQuery('now()').knexQuery)

      table.index(['timestamp'])
    })
  }

  async down() {
    this.schema.dropTable(this.tableName)
  }
}
