import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  protected tableName = 'website_visits'

  async up() {
    this.schema.createTable(this.tableName, (table) => {
      table.uuid('id').primary().defaultTo(this.db.rawQuery('gen_random_uuid()').knexQuery)
      table.string('url', 2048).notNullable()
      table.string('domain', 253).notNullable()
      // Duration in seconds the tab was the active focused tab
      table.integer('active_duration').notNullable().defaultTo(0)
      // Duration in seconds the tab was playing audio/video in the background
      table.integer('audio_video_duration').notNullable().defaultTo(0)
      table.timestamp('start_time', { useTz: true }).notNullable()
      table.timestamp('end_time', { useTz: true }).notNullable()
      // UUID generated by the extension — used for server-side deduplication
      table.string('client_id').notNullable().unique()
      table
        .timestamp('created_at', { useTz: true })
        .notNullable()
        .defaultTo(this.db.rawQuery('now()').knexQuery)

      table.index(['domain'])
      table.index(['start_time'])
    })
  }

  async down() {
    this.schema.dropTable(this.tableName)
  }
}
