/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class MoodLogSchema extends BaseModel {
  static $columns = ['clientId', 'createdAt', 'id', 'mood', 'timestamp'] as const
  $columns = MoodLogSchema.$columns
  @column()
  declare clientId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mood: number
  @column.dateTime()
  declare timestamp: DateTime
}

export class WebsiteVisitSchema extends BaseModel {
  static $columns = ['activeDuration', 'audioVideoDuration', 'clientId', 'createdAt', 'domain', 'endTime', 'id', 'startTime', 'url'] as const
  $columns = WebsiteVisitSchema.$columns
  @column()
  declare activeDuration: number
  @column()
  declare audioVideoDuration: number
  @column()
  declare clientId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare domain: string
  @column.dateTime()
  declare endTime: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare startTime: DateTime
  @column()
  declare url: string
}
