/**
 * This file is automatically generated by Lucid schema generation.
 * DO NOT EDIT manually — run "node ace migration:run" to re-generate.
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class MoodLogSchema extends BaseModel {
  static $columns = ['id', 'mood', 'timestamp', 'clientId', 'createdAt'] as const
  $columns = MoodLogSchema.$columns

  @column({ isPrimary: true })
  declare id: string

  @column()
  declare mood: number

  @column.dateTime()
  declare timestamp: DateTime

  @column()
  declare clientId: string

  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class WebsiteVisitSchema extends BaseModel {
  static $columns = [
    'id',
    'url',
    'domain',
    'activeDuration',
    'audioVideoDuration',
    'startTime',
    'endTime',
    'clientId',
    'createdAt',
  ] as const
  $columns = WebsiteVisitSchema.$columns

  @column({ isPrimary: true })
  declare id: string

  @column()
  declare url: string

  @column()
  declare domain: string

  @column()
  declare activeDuration: number

  @column()
  declare audioVideoDuration: number

  @column.dateTime()
  declare startTime: DateTime

  @column.dateTime()
  declare endTime: DateTime

  @column()
  declare clientId: string

  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}
